version: '3'
services:
  postgres-auth:
    image: postgres:alpine
    container_name: postgres-auth
    restart: unless-stopped
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=authDB
  postgres-resource:
    image: postgres:alpine
    container_name: postgres-resource
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=resourceDB
