server:
  port: 8083

spring:
  application:
    name: PROFILE-SERVICE
  banner:
    location: classpath:/static/banner.txt
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]

amazonProperties:
  endpointUrl: https://s3.us-east-1.amazonaws.com
  accessKey: ${ACCESS_AWS_KEY}
  secretKey: ${SECRET_AWS_KEY}
  bucketName: ustbazaar
  region: us-east-1